application: address-parser
version: 1
runtime: python
api_version: 1

handlers:
- url: /parse
  script: main.py

- url: /areas
  script: main.py

- url: /areas/[\w-]+
  script: main.py

- url: /excludeWords
  script: main.py

- url: /
  static_dir: ./

  